# Generated by Django 3.2.10 on 2022-12-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20220819_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['id'], 'verbose_name': 'CommentModel', 'verbose_name_plural': 'CommentModel'},
        ),
    ]
