# Generated by Django 3.2.10 on 2022-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_forummodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
